// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addcommentstoeventregistration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcommentstoeventregistration));
        
        string IMigrationMetadata.Id
        {
            get { return "201503100936406_add-comments-to-event-registration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
