// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addbonusandpricetoevents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbonusandpricetoevents));
        
        string IMigrationMetadata.Id
        {
            get { return "201503060959323_add-bonus-and-price-to-events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
