// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addtalentecheckhighscores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtalentecheckhighscores));
        
        string IMigrationMetadata.Id
        {
            get { return "201503161631346_add-talentecheck-highscores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
