// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addeventfeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeventfeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "201503090907547_add-event-feedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
