// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addeventidtoeventfeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeventidtoeventfeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091231078_add-event-id-to-event-feedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
