// <auto-generated />
namespace Talentify.ORM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addfollowupflagtoevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfollowupflagtoevent));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091626589_add-followup-flag-to-event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
